"""Single machine-readable contract for Kirin Tor authoring projections.

The parser and semantic engine remain authoritative.  This module exposes the
closed public vocabulary that editor projections need, so highlighting,
completion, indentation and syntax-reference routing do not maintain separate
hand-written dialects.
"""

from __future__ import annotations

from typing import Final


AUTHORING_CONTRACT_VERSION: Final = 1

DIRECTIVES: Final = ("kirin", "entry", "game-version", "status")
LITERALS: Final = ("true", "false")
COMPOUND_KEYWORDS: Final = ("one-of",)
CLOSE_BRACKETS: Final = ("(", "[", '"')

TOP_LEVEL_DECLARATIONS: Final = (
    "dimension",
    "unit",
    "domain",
    "source",
    "alias",
    "input",
    "field",
    "require",
    "function",
    "output",
    "group",
    "preset",
    "table",
    "distribution",
    "display",
    "chart",
    "type",
    "process",
    "scenario",
    "analysis",
)

NESTED_SECTIONS: Final = (
    "bounds",
    "markers",
    "objectives",
    "outcomes",
    "phases",
    "points",
    "policies",
    "search",
    "sequence",
    "series",
    "variants",
    "y",
)

SYNTAX_KEYWORDS: Final = (
    "action",
    "adaptive_dyadic",
    "after",
    "analysis",
    "and",
    "as",
    "at",
    "bounds",
    "branch",
    "cancel",
    "citation",
    "chart",
    "choose",
    "compare",
    "connect",
    "continuously",
    "cycle",
    "coefficient_percent",
    "decide",
    "decision",
    "decision_surface",
    "default",
    "digest",
    "digits",
    "emit",
    "event",
    "every",
    "export_csv",
    "export_svg",
    "flow",
    "from",
    "game_version",
    "horizon",
    "in",
    "independent",
    "input",
    "integer",
    "internal",
    "joint",
    "key",
    "kind",
    "let",
    "location",
    "markers",
    "maximize",
    "maximum_branches",
    "maximum_decisions",
    "maximum_entities",
    "maximum_evaluations",
    "maximum_events",
    "measure",
    "method",
    "minimize",
    "next",
    "not",
    "objective",
    "objectives",
    "observe",
    "on",
    "operation",
    "optimize",
    "or",
    "otherwise",
    "output",
    "outcomes",
    "pareto",
    "percent",
    "phase",
    "phases",
    "policies",
    "policy",
    "probability",
    "points",
    "range",
    "reach",
    "reduce",
    "replace",
    "require",
    "run",
    "schedule",
    "search",
    "send",
    "sequence",
    "series",
    "state",
    "steady",
    "stop",
    "target",
    "then",
    "time_tolerance",
    "title",
    "to",
    "times",
    "trajectory",
    "until",
    "up",
    "use",
    "using",
    "value",
    "variant",
    "variant_comparison",
    "variants",
    "verified_at",
    "wait",
    "when",
    "x",
    "x_direction",
    "x_label",
    "y",
    "y_direction",
    "y_label",
)

TYPE_KEYWORDS: Final = (
    "boolean",
    "count",
    "dimensionless",
    "event_id",
    "integer",
    "list",
    "map",
    "millisecond",
    "nonnegative_integer",
    "number",
    "positive_integer",
    "probability",
    "second",
    "time",
)

OPERATORS: Final = ("->", "==", "!=", "<=", ">=", "**", "+", "-", "*", "/", "=", "@", ":", "..")

PROCESS_EXPRESSION_BUILTINS: Final = {
    "abs": "abs(value)",
    "all": "all(values)",
    "any": "any(values)",
    "argmax": "argmax(values)",
    "argmin": "argmin(values)",
    "ceil": "ceil(value)",
    "contains": "contains(collection, value)",
    "empty": "empty()",
    "filter": "filter(collection, mask)",
    "floor": "floor(value)",
    "get": "get(map_value, key)",
    "if_else": "if_else(condition, when_true, when_false)",
    "max": "max(value, ...)",
    "min": "min(value, ...)",
    "put": "put(map_value, key, value)",
    "remove": "remove(map_value, key)",
    "size": "size(collection)",
    "sqrt": "sqrt(value)",
    "sum": "sum(values)",
}

RUNTIME_MEASURE_SYMBOLS: Final = {
    "elapsed": "运行至当前采样点的时间",
    "event_count": "当前已处理的事件数",
    "decision_count": "当前已处理的决策数",
    "horizon": "Scenario 声明的时间上限",
}

REFERENCE_IDENTITIES: Final = {
    "entry": {"topic": "document", "symbol": "document-header"},
    "alias": {"topic": "aliases", "symbol": "alias"},
    "source": {"topic": "aliases", "symbol": "source"},
    "input": {"topic": "members", "symbol": "input"},
    "field": {"topic": "members", "symbol": "field"},
    "function": {"topic": "members", "symbol": "function"},
    "output": {"topic": "members", "symbol": "output"},
    "preset": {"topic": "presets", "symbol": "preset"},
    "table": {"topic": "tables", "symbol": "table"},
    "distribution": {"topic": "distributions", "symbol": "distribution"},
    "type": {"topic": "structures", "symbol": "type"},
    "type_field": {"topic": "structures", "symbol": "type"},
    "object": {"topic": "structures", "symbol": "object"},
    "object_field": {"topic": "structures", "symbol": "object"},
    "process": {"topic": "process", "symbol": "process-declarations"},
    "scenario": {"topic": "process", "symbol": "scenario"},
    "analysis": {"topic": "process", "symbol": "analysis"},
    "measure": {"topic": "process", "symbol": "scenario-measures-objectives"},
    "dimension": {"topic": "semantics", "symbol": "dimension"},
    "unit": {"topic": "semantics", "symbol": "unit"},
    "domain": {"topic": "semantics", "symbol": "numeric-domain"},
    "chart": {"topic": "charts", "symbol": "static-chart"},
    "process_input": {"topic": "process", "symbol": "process-declarations"},
    "process_state": {"topic": "process", "symbol": "process-declarations"},
    "process_event": {"topic": "process", "symbol": "process-declarations"},
    "process_action": {"topic": "process", "symbol": "process-declarations"},
    "process_observation": {"topic": "process", "symbol": "process-declarations"},
    "process_key": {"topic": "process", "symbol": "process-declarations"},
    "process_phase": {"topic": "process", "symbol": "process-declarations"},
    "scenario_instance": {"topic": "process", "symbol": "scenario"},
    "scenario_variant": {"topic": "process", "symbol": "scenario"},
    "scenario_action": {"topic": "process", "symbol": "scenario"},
    "scenario_policy": {"topic": "process", "symbol": "scenario-policies-decisions"},
    "scenario_measure": {"topic": "process", "symbol": "scenario-measures-objectives"},
    "scenario_objective": {"topic": "process", "symbol": "scenario-measures-objectives"},
    "analysis_chart": {"topic": "process", "symbol": "analysis-chart"},
}

# Each tuple is (label, trigger, English detail, insertion, priority, contexts,
# syntax-reference section, exact syntax-reference item).
AUTHORING_SNIPPETS: Final = (
    ("条目文档", "条目文档", "entry document", '@kirin 2\n@entry entry_id "中文标题"\n\n$0', 1, ("document", "top"), "document", "document-header"),
    ("游戏版本元数据", "game-version", "game version metadata", '@game-version "$0"', 5, ("document", "top"), "document", "metadata-directives"),
    ("校验状态元数据", "status", "validation status metadata", '@status "$0"', 5, ("document", "top"), "document", "metadata-directives"),
    ("输入声明", "输入", "input", 'input name "显示名": number[dimensionless] = $0', 10, ("top",), "members", "input"),
    ("别名声明", "别名", "alias", "alias 中文名 = entry.member$0", 11, ("top",), "aliases", "alias"),
    ("字段声明", "字段", "field", 'field value "显示名": dimensionless = $0', 12, ("top",), "members", "field"),
    ("函数声明", "函数", "function", 'function function_name "显示名"(arg: number[dimensionless]): dimensionless = $0', 13, ("top",), "members", "function"),
    ("查表声明", "查表", "table", 'table table_name "显示名":\n  input = dimensionless\n  output = dimensionless\n  points:\n    1 = $0', 14, ("top",), "tables", "table"),
    ("有限分布声明", "有限分布", "distribution", 'distribution result_distribution "显示名": dimensionless:\n  outcomes:\n    - 0 @ 1 - probability_value\n    - 1 @ $0', 14, ("top",), "distributions", "distribution"),
    ("输出声明", "输出", "output", 'output result "显示名": dimensionless = $0', 14, ("top",), "members", "output"),
    ("分组声明", "分组", "group", 'group group_id "显示名":\n  - result$0', 15, ("top",), "presets", "group"),
    ("参数方案声明", "参数方案", "preset", 'preset preset_id "显示名":\n  entry.input = $0', 16, ("top",), "presets", "preset"),
    ("显示声明", "显示", "display", "display result = number digits $0", 17, ("top",), "presets", "display"),
    ("约束声明", "约束", "require", "require $0", 15, ("top", "process_decl"), "members", "require"),
    ("来源声明", "来源", "source", 'source note:\n  citation = "$0"', 17, ("top",), "aliases", "source"),
    ("量纲声明", "量纲", "dimension", 'dimension quantity "显示名"$0', 15, ("top",), "semantics", "dimension"),
    ("单位声明", "单位", "unit", "unit unit_id = dimension_id$0", 15, ("top",), "semantics", "unit"),
    ("数值值域", "值域", "domain", 'domain domain_id "显示名": dimensionless in 0..1$0', 15, ("top",), "semantics", "numeric-domain"),
    ("符号值域", "符号值域", "symbolic domain", 'domain status "显示名":\n  - active "启用"\n  - inactive "停用"$0', 15, ("top",), "semantics", "symbolic-domain"),
    ("结构类型", "结构", "type", 'type type_id "显示名":\n  field_name: dimensionless$0', 15, ("top",), "structures", "type"),
    ("类型化对象", "对象", "typed object", 'type_id object_id "显示名":\n  field_name = $0', 16, ("top",), "structures", "object"),
    ("类型字段", "类型字段", "type field", 'field_name "显示名": dimensionless$0', 10, ("type_field",), "structures", "type"),
    ("有界过程", "过程", "process", "process mechanism:\n  state value: count = 0\n  event input step()\n  on step():\n    next value = value + 1\n  observe current: count = value$0", 16, ("top",), "process", "process-declarations"),
    ("Process 输入", "过程输入", "process input", 'input name "显示名": number[dimensionless] = $0', 10, ("process_decl",), "process", "process-declarations"),
    ("Process 状态", "状态", "state", 'state name "显示名": count = $0', 10, ("process_decl",), "process", "process-declarations"),
    ("Process key", "key", "key", "key key_id$0", 11, ("process_decl",), "process", "process-declarations"),
    ("Process phase", "phase", "phase", "phase phase_id$0", 11, ("process_decl",), "process", "process-declarations"),
    ("输入事件", "输入事件", "input event", "event input event_id($0)", 11, ("process_decl",), "process", "process-declarations"),
    ("输出事件", "输出事件", "output event", "event output event_id($0)", 11, ("process_decl",), "process", "process-declarations"),
    ("内部事件", "内部事件", "internal event", "event internal event_id($0)", 11, ("process_decl",), "process", "process-declarations"),
    ("Process action", "动作", "action", "action action_id($0)", 12, ("process_decl",), "process", "process-declarations"),
    ("连续 flow", "flow", "flow", "flow state_id(current, elapsed) = $0", 12, ("process_decl",), "process", "process-declarations"),
    ("事件处理器", "处理器", "handler", "on event_id():\n  $0", 12, ("process_decl",), "process", "process-declarations"),
    ("公开观察值", "观察", "observe", 'observe value "显示名": dimensionless = $0', 12, ("process_decl",), "process", "process-declarations"),
    ("局部值", "局部", "let effect", "let value: dimensionless = $0", 10, ("process_effect",), "process", "process-effects"),
    ("更新状态", "更新", "next effect", "next state_id = $0", 10, ("process_effect",), "process", "process-effects"),
    ("发射事件", "发射", "emit effect", "emit event_id($0)", 11, ("process_effect",), "process", "process-effects"),
    ("调度事件", "调度", "schedule effect", "schedule event_id() after 1 second phase phase_id key $0", 11, ("process_effect",), "process", "process-effects"),
    ("替换调度", "替换", "replace effect", "replace event_id() after 1 second phase phase_id key $0", 11, ("process_effect",), "process", "process-effects"),
    ("取消调度", "取消", "cancel effect", "cancel $0", 11, ("process_effect",), "process", "process-effects"),
    ("条件效果", "条件效果", "when effect", "when condition:\n  $0", 12, ("process_effect",), "process", "process-effects"),
    ("概率分支", "概率分支", "branch effect", "branch branch_id independent:\n  probability 1:\n    $0", 12, ("process_effect",), "process", "process-effects"),
    ("概率 case", "概率", "probability case", "probability expression:\n  $0", 10, ("process_probability",), "process", "process-effects"),
    ("过程场景", "场景", "scenario process", "scenario trial:\n  phases:\n    - event\n    - decision\n  use actor = mechanism:\n  bounds:\n    horizon = 10 second\n    maximum_events = 100\n    maximum_decisions = 10\n    maximum_branches = 100\n    maximum_entities = 1$0", 17, ("top",), "process", "scenario"),
    ("Scenario phases", "阶段", "scenario phases", "phases:\n  - phase_id$0", 10, ("scenario_decl",), "process", "scenario"),
    ("Process 实例", "实例", "scenario use", "use actor = entry.process_id:\n  $0", 10, ("scenario_decl",), "process", "scenario"),
    ("Scenario variant", "变体", "scenario variant", "variant variant_id:\n  actor.input_id = $0", 11, ("scenario_decl",), "process", "scenario"),
    ("连接事件", "连接", "scenario connect", "connect actor.output_event -> target.input_event$0", 11, ("scenario_decl",), "process", "scenario"),
    ("定时发送", "定时", "scenario at", "at 0 second phase phase_id:\n  send actor.event()$0", 12, ("scenario_decl",), "process", "scenario"),
    ("周期发送", "周期", "scenario every", "every 1 second from 0 second until 10 second phase phase_id:\n  send actor.event()$0", 12, ("scenario_decl",), "process", "scenario"),
    ("Scenario action", "场景动作", "scenario action", "action action_id:\n  send actor.event()$0", 12, ("scenario_decl",), "process", "scenario"),
    ("固定策略", "策略", "policy", "policy policy_id:\n  choose action_id when condition\n  otherwise wait$0", 12, ("scenario_decl",), "process", "scenario-policies-decisions"),
    ("周期决策", "周期决策", "decide every", "decide every 1 second from 0 second until 10 second phase phase_id:\n  - action_id\n  - wait$0", 13, ("scenario_decl",), "process", "scenario-policies-decisions"),
    ("事件后决策", "事件后决策", "decide after", "decide after actor.event phase phase_id:\n  - action_id$0", 13, ("scenario_decl",), "process", "scenario-policies-decisions"),
    ("条件决策", "条件决策", "decide when", "decide when condition phase phase_id:\n  - action_id$0", 13, ("scenario_decl",), "process", "scenario-policies-decisions"),
    ("连续决策", "连续决策", "decide continuously", "decide continuously up to 10 times from 0 second until 10 second phase phase_id:\n  - action_id$0", 13, ("scenario_decl",), "process", "scenario-policies-decisions"),
    ("轨迹度量", "度量", "measure trajectory", "measure minimum_value: number[dimensionless] = minimum_over_time(actor.current)$0", 14, ("scenario_decl",), "process", "scenario-measures-objectives"),
    ("优化目标", "目标", "objective optimize", "objective best:\n  maximize result_measure\n  then minimize cost_measure$0", 14, ("scenario_decl",), "process", "scenario-measures-objectives"),
    ("停止条件", "停止", "scenario stop", "stop when $0", 14, ("scenario_decl",), "process", "scenario"),
    ("执行边界", "边界", "scenario bounds", "bounds:\n  horizon = 10 second\n  maximum_events = 100\n  maximum_decisions = 10\n  maximum_branches = 100\n  maximum_entities = 1$0", 14, ("scenario_decl",), "process", "scenario"),
    ("Process analysis", "过程分析", "analysis process", "analysis search:\n  using = trial\n  operation = optimize\n  objectives:\n    - best$0", 19, ("top",), "process", "analysis"),
    ("选择 Scenario", "using", "analysis using", "using = $0", 10, ("analysis_decl",), "process", "analysis"),
    ("选择操作", "operation", "analysis operation", "operation = $0", 10, ("analysis_decl",), "process", "analysis"),
    ("选择 Policy", "policy", "analysis policy", "policy = $0", 11, ("analysis_decl",), "process", "analysis"),
    ("Policy 列表", "policies", "analysis policies", "policies:\n  - $0", 11, ("analysis_decl",), "process", "analysis"),
    ("Objective 列表", "objectives", "analysis objectives", "objectives:\n  - $0", 11, ("analysis_decl",), "process", "analysis"),
    ("Variant 列表", "variants", "analysis variants", "variants:\n  - $0", 11, ("analysis_decl",), "process", "analysis"),
    ("Reach target", "target", "analysis target", "target = $0", 12, ("analysis_decl",), "process", "analysis"),
    ("搜索设置", "搜索", "analysis search", "search:\n  method = adaptive_dyadic\n  time_tolerance = 1/1000 second\n  maximum_evaluations = 1000$0", 12, ("analysis_decl",), "process", "analysis"),
    ("分析图表", "分析图表", "analysis chart", "chart chart_id:\n  kind = trajectory\n  series:\n    - actor.observation$0", 13, ("analysis_decl",), "process", "analysis-chart"),
    ("搜索 method", "method", "search method", "method = adaptive_dyadic$0", 10, ("analysis_search",), "process", "analysis"),
    ("搜索时间容差", "时间容差", "search time tolerance", "time_tolerance = 1/1000 second$0", 10, ("analysis_search",), "process", "analysis"),
    ("搜索预算", "搜索预算", "search budget", "maximum_evaluations = 1000$0", 10, ("analysis_search",), "process", "analysis"),
    ("图表类型", "图表类型", "analysis chart kind", "kind = $0", 10, ("analysis_chart",), "process", "analysis-chart"),
    ("图表 series", "series", "analysis chart series", "series:\n  - $0", 10, ("analysis_chart",), "process", "analysis-chart"),
    ("图表 markers", "markers", "analysis chart markers", "markers:\n  - event actor.event$0", 10, ("analysis_chart",), "process", "analysis-chart"),
    ("图表 x", "x", "analysis chart x", "x = $0", 11, ("analysis_chart",), "process", "analysis-chart"),
    ("图表 y", "y", "analysis chart y", "y = $0", 11, ("analysis_chart",), "process", "analysis-chart"),
    ("图表 value", "value", "analysis chart value", "value = $0", 11, ("analysis_chart",), "process", "analysis-chart"),
    ("图表 x 方向", "x方向", "analysis chart x direction", "x_direction = $0", 11, ("analysis_chart",), "process", "analysis-chart"),
    ("图表 y 方向", "y方向", "analysis chart y direction", "y_direction = $0", 11, ("analysis_chart",), "process", "analysis-chart"),
    ("图表 SVG 导出", "SVG导出", "analysis chart svg", 'export_svg = "$0"', 12, ("analysis_chart",), "process", "analysis-chart"),
    ("图表 CSV 导出", "CSV导出", "analysis chart csv", 'export_csv = "$0"', 12, ("analysis_chart",), "process", "analysis-chart"),
    ("发送事件", "send", "scenario send", "send actor.event($0)", 10, ("scenario_send",), "process", "scenario"),
    ("策略条件", "choose", "policy rule", "choose action_id when $0", 10, ("scenario_policy",), "process", "scenario-policies-decisions"),
    ("策略默认", "otherwise", "policy otherwise", "otherwise wait$0", 11, ("scenario_policy",), "process", "scenario-policies-decisions"),
    ("策略序列", "sequence", "policy sequence", "sequence:\n  - action_id$0", 11, ("scenario_policy",), "process", "scenario-policies-decisions"),
    ("Table input", "table input", "table input", "input = $0", 10, ("table_body",), "tables", "table"),
    ("Table output", "table output", "table output", "output = $0", 10, ("table_body",), "tables", "table"),
    ("Table points", "points", "table points", "points:\n  0 = $0", 10, ("table_body",), "tables", "table"),
    ("Distribution outcomes", "outcomes", "distribution outcomes", "outcomes:\n  - value @ $0", 10, ("distribution_body",), "distributions", "distribution"),
    ("静态图表 x", "chart x", "static chart x", "x = $0", 10, ("chart_body",), "charts", "static-chart"),
    ("静态图表范围", "range", "static chart range", "range = 0..$0", 10, ("chart_body",), "charts", "static-chart"),
    ("静态图表采样数", "points", "static chart points", "points = $0", 10, ("chart_body",), "charts", "static-chart"),
    ("静态图表曲线", "chart y", "static chart y", "y:\n  - $0", 10, ("chart_body",), "charts", "static-chart"),
    ("静态图表标题", "title", "static chart title", 'title = "$0"', 11, ("chart_body",), "charts", "static-chart"),
    ("静态图表横轴标签", "x label", "static chart x label", 'x_label = "$0"', 11, ("chart_body",), "charts", "static-chart"),
    ("静态图表纵轴标签", "y label", "static chart y label", 'y_label = "$0"', 11, ("chart_body",), "charts", "static-chart"),
    ("静态图表 SVG 导出", "chart svg", "static chart svg", 'export_svg = "$0"', 12, ("chart_body",), "charts", "static-chart"),
    ("静态图表 CSV 导出", "chart csv", "static chart csv", 'export_csv = "$0"', 12, ("chart_body",), "charts", "static-chart"),
    ("来源引用", "citation", "source citation", 'citation = "$0"', 10, ("source_body",), "aliases", "source"),
    ("来源类别", "source kind", "source kind", "kind = $0", 11, ("source_body",), "aliases", "source"),
    ("来源定位", "location", "source location", 'location = "$0"', 11, ("source_body",), "aliases", "source"),
    ("来源核验日期", "verified at", "source verified date", 'verified_at = "$0"', 11, ("source_body",), "aliases", "source"),
    ("来源摘要", "digest", "source digest", 'digest = "sha256:$0"', 11, ("source_body",), "aliases", "source"),
    ("来源游戏版本", "source game version", "source game version", 'game_version = "$0"', 11, ("source_body",), "aliases", "source"),
    ("长说明块", "长说明", "description", "---\n$0\n---", 18, ("top",), "document", "comments-and-prose"),
    ("图表配置", "图表", "plot", "chart preview:\n  x = entry.input\n  range = 0..1\n  points = 101\n  y:\n    - entry.output\n  export_svg = \"results/chart.svg\"\n  export_csv = \"results/chart.csv\"$0", 20, ("top",), "charts", "static-chart"),
    ("分段公式", "分段", "piecewise", "piecewise(\n  condition, value,\n  $0\n)", 21, ("static_expr",), "members", "scalar-expression"),
    ("条件公式", "条件", "if_else", "if_else(condition, when_true, $0)", 22, ("static_expr", "process_expr"), "members", "scalar-expression"),
)


def public_authoring_contract() -> dict:
    """Return the JSON-safe editor contract sent with Workbench bootstrap."""

    return {
        "version": AUTHORING_CONTRACT_VERSION,
        "indent_width": 2,
        "line_comment": "//",
        "prose_fence_pattern": "^-{3,}$",
        "close_brackets": list(CLOSE_BRACKETS),
        "tokens": {
            "directives": list(DIRECTIVES),
            "top_level_declarations": list(TOP_LEVEL_DECLARATIONS),
            "nested_sections": list(NESTED_SECTIONS),
            "keywords": list(SYNTAX_KEYWORDS),
            "types": list(TYPE_KEYWORDS),
            "literals": list(LITERALS),
            "compound_keywords": list(COMPOUND_KEYWORDS),
            "operators": list(OPERATORS),
        },
        "reference_identities": REFERENCE_IDENTITIES,
        "process_expression_builtins": [
            {"name": name, "signature": signature}
            for name, signature in PROCESS_EXPRESSION_BUILTINS.items()
        ],
        "runtime_measure_symbols": [
            {"name": name, "description": description}
            for name, description in RUNTIME_MEASURE_SYMBOLS.items()
        ],
    }
