"""Offline, non-executing author tools for Workbench Plugin API 2."""

from __future__ import annotations

import hashlib
import json
import os
import shutil
import tempfile
import zipfile
from pathlib import Path
from typing import Optional

from .errors import PluginError, WorkspaceError
from .package_manifest import current_feature_line
from .package_store import locked_workspace_resolution
from .plugin_artifacts import render_sdk_mjs, render_sdk_types
from .plugin_manifest import (
    PLUGIN_ID_RE,
    PLUGIN_SCHEMA_VERSION,
    canonical_plugin_sha256,
    load_plugin_manifest,
    plugin_content_paths,
)
from .plugin_protocol import PLUGIN_API_VERSION, plugin_protocol_descriptor
from .plugin_store import plugin_compatibility
from .workspace import Workspace, initialize


def _atomic_scaffold(target: Path, files: dict[str, str]) -> Path:
    target = target.expanduser().resolve()
    if target.exists():
        raise PluginError(f"plugin directory already exists: {target}")
    target.parent.mkdir(parents=True, exist_ok=True)
    staging_root = Path(
        tempfile.mkdtemp(prefix=f".{target.name}-plugin-", dir=str(target.parent))
    )
    staged = staging_root / target.name
    try:
        for relative, text in files.items():
            path = staged / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
        load_plugin_manifest(staged)
        os.replace(staged, target)
    finally:
        shutil.rmtree(staging_root, ignore_errors=True)
    return target


def create_plugin_template(directory: Path, plugin_id: str) -> dict:
    plugin_id = plugin_id.strip()
    if not PLUGIN_ID_RE.fullmatch(plugin_id):
        raise PluginError("plugin id must be a dotted lower-case id")
    surface_id = f"{plugin_id}.main"
    manifest = {
        "schema": PLUGIN_SCHEMA_VERSION,
        "id": plugin_id,
        "name": plugin_id.rsplit(".", 1)[-1].replace("-", " ").title(),
        "version": "0.1.0",
        "api": PLUGIN_API_VERSION,
        "description": "A sandboxed Kirin Tor Workbench presentation plugin.",
        "license": "UNLICENSED",
        "requires": {
            "kirin_feature": current_feature_line(),
            "interfaces": [],
        },
        "contributes": {
            "renderers": [],
            "views": [
                {
                    "id": surface_id,
                    "title": "Plugin view",
                    "description": "Minimal SDK-backed Plugin view.",
                    "entry": "web/index.html",
                    "permissions": ["workspace.summary", "model.read"],
                }
            ],
            "tools": [],
            "commands": [],
            "profiles": [],
        },
    }
    files = {
        "kirin.plugin.json": json.dumps(
            manifest, ensure_ascii=False, indent=2, sort_keys=True
        )
        + "\n",
        "web/index.html": """<!doctype html>
<html lang="en">
  <head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Kirin Tor Plugin</title></head>
  <body><main id="app">Waiting for Kirin Tor…</main><script type="module" src="plugin.js"></script></body>
</html>
""",
        "web/plugin.js": """import { createKirinPlugin } from "./kirin-plugin-sdk.mjs";

const kirin = createKirinPlugin({ api: 2 });
const app = document.querySelector("#app");
kirin.onContext((context) => {
  const count = context.catalog?.descriptor_count ?? 0;
  app.textContent = `Validated model descriptors: ${count}`;
});
await kirin.ready();
""",
        "web/kirin-plugin-sdk.mjs": render_sdk_mjs(),
        "web/kirin-plugin-sdk.d.mts": render_sdk_types(),
        "tests/protocol-smoke.json": json.dumps(
            {
                "api": PLUGIN_API_VERSION,
                "surface": surface_id,
                "required_context": ["catalog"],
            },
            indent=2,
            sort_keys=True,
        )
        + "\n",
        "README.md": f"""# {plugin_id}

This Plugin was generated by `kt plugin new`. It uses the vendored Kirin Tor Plugin SDK and
contains presentation code only. Edit `kirin.plugin.json`, then run `kt plugin check .` and
`kt plugin test . --workspace /path/to/workspace` before bundling.
""",
        "LICENSE.placeholder": "Replace this file and the manifest license before publishing.\n",
    }
    root = _atomic_scaffold(directory, files)
    return check_plugin(root)


def check_plugin(directory: Path, workspace: Optional[Path] = None) -> dict:
    root = directory.expanduser().resolve()
    manifest = load_plugin_manifest(root)
    paths = plugin_content_paths(root)
    result = {
        "status": "ok",
        "root": str(root),
        "id": manifest.id,
        "version": manifest.version,
        "api": manifest.api,
        "files": len(paths),
        "content_sha256": canonical_plugin_sha256(root),
        "permissions": sorted(
            {
                permission
                for group in (
                    manifest.contributes.renderers,
                    manifest.contributes.views,
                    manifest.contributes.tools,
                )
                for contribution in group
                for permission in contribution.permissions
            }
        ),
        "requires": manifest.requires.as_dict(),
        "protocol": plugin_protocol_descriptor(),
    }
    if workspace is not None:
        workspace_root = Workspace.find_root(workspace.expanduser().resolve())
        resolution = locked_workspace_resolution(workspace_root)
        result["compatibility"] = plugin_compatibility(manifest, resolution)
    return result


def _copy_disposable_workspace(source: Path, target: Path) -> None:
    shutil.copytree(
        source,
        target,
        ignore=shutil.ignore_patterns(
            ".git",
            "runs",
            "artifacts",
            "kirin.plugins.toml",
            "kirin.plugins.lock",
            "plugin-approvals.json",
            "workbench-recovery.json",
        ),
    )
    shutil.rmtree(target / ".kirin" / "plugins", ignore_errors=True)


def test_plugin(directory: Path, workspace: Path) -> dict:
    """Run offline protocol fixtures without installing or executing Plugin code."""

    source_workspace = Workspace.find_root(workspace.expanduser().resolve())
    checked = check_plugin(directory)
    with tempfile.TemporaryDirectory(prefix="kirin-plugin-test-") as temporary:
        disposable = Path(temporary) / "workspace"
        _copy_disposable_workspace(source_workspace, disposable)
        if not (disposable / "kirin.workspace").is_file():
            initialize(disposable)
        loaded = Workspace.load(disposable)
        resolution = locked_workspace_resolution(disposable)
        manifest = load_plugin_manifest(directory)
        compatibility = plugin_compatibility(manifest, resolution)
        if not compatibility["compatible"]:
            raise PluginError("Plugin requirements are not satisfied by the disposable workspace")
        if not loaded.documents:
            raise WorkspaceError("disposable Plugin test workspace has no validated documents")
        return {
            **checked,
            "suite": "offline-protocol-v2",
            "workspace_revision_documents": len(loaded.documents),
            "compatibility": compatibility,
            "tests": [
                {"name": "manifest", "status": "passed"},
                {"name": "content-digest", "status": "passed"},
                {"name": "disposable-workspace", "status": "passed"},
                {"name": "interface-requirements", "status": "passed"},
                {"name": "capability-permissions", "status": "passed"},
            ],
        }


def bundle_plugin(
    directory: Path,
    output: Optional[Path] = None,
    *,
    force: bool = False,
) -> dict:
    """Create a deterministic static archive without running a build script."""

    root = directory.expanduser().resolve()
    checked = check_plugin(root)
    manifest = load_plugin_manifest(root)
    destination = (
        output.expanduser().resolve()
        if output is not None
        else root.parent / f"{manifest.id}-{manifest.version}.ktplugin.zip"
    )
    try:
        destination.relative_to(root)
    except ValueError:
        pass
    else:
        raise PluginError("plugin bundle output must be outside the plugin root")
    if destination.exists() and not force:
        raise PluginError(
            f"plugin bundle already exists; pass --force to replace it: {destination}"
        )
    destination.parent.mkdir(parents=True, exist_ok=True)
    temporary = destination.with_name(f".{destination.name}.{os.getpid()}.tmp")
    try:
        with zipfile.ZipFile(
            temporary,
            "w",
            compression=zipfile.ZIP_DEFLATED,
            compresslevel=9,
        ) as archive:
            for path in plugin_content_paths(root):
                relative = path.relative_to(root).as_posix()
                info = zipfile.ZipInfo(relative, date_time=(1980, 1, 1, 0, 0, 0))
                info.compress_type = zipfile.ZIP_DEFLATED
                info.external_attr = 0o100644 << 16
                info.create_system = 3
                archive.writestr(info, path.read_bytes())
        os.replace(temporary, destination)
    finally:
        temporary.unlink(missing_ok=True)
    archive_sha256 = hashlib.sha256(destination.read_bytes()).hexdigest()
    return {
        **checked,
        "bundle": str(destination),
        "bundle_bytes": destination.stat().st_size,
        "bundle_sha256": archive_sha256,
    }
